# Generated by Django 4.1.3 on 2022-12-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default=13, max_length=75),
            preserve_default=False,
        ),
    ]
