# Generated by Django 4.1.3 on 2022-12-18 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_messages_clientmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmessage',
            name='sent_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
