# Generated by Django 4.1.3 on 2022-12-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('PHONES', 'Phones'), ('LAPTOPS', 'Laptops'), ('TV', 'TV'), ('COMPUTERS_AND_COMPONENTS', 'Computers & Computer components'), ('SMART_WATCHES', 'Smart Watches'), ('PHOTOGRAPHY', 'Photography'), ('GAMING_CONSOLES', 'Gaming consoles'), ('HEADPHONES', 'Headphones'), ('TABLETS', 'Tablets'), ('AUDIO', 'Audio'), ('STORAGE', 'Storage')], max_length=50, null=True),
        ),
    ]
