# Generated by Django 4.1.3 on 2022-12-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_submited',
            field=models.BooleanField(default=False),
        ),
    ]
