# Generated by Django 4.1.3 on 2022-11-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
